# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from REF2CLI import messages_pb2 as REF2CLI_dot_messages__pb2
import common_pb2 as common__pb2


class RefereeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/fira_message.ref_to_cli.Referee/Register',
        request_serializer=REF2CLI_dot_messages__pb2.TeamInfo.SerializeToString,
        response_deserializer=REF2CLI_dot_messages__pb2.TeamName.FromString,
        )
    self.RunStrategy = channel.unary_unary(
        '/fira_message.ref_to_cli.Referee/RunStrategy',
        request_serializer=REF2CLI_dot_messages__pb2.Environment.SerializeToString,
        response_deserializer=REF2CLI_dot_messages__pb2.Command.FromString,
        )
    self.SetBall = channel.unary_unary(
        '/fira_message.ref_to_cli.Referee/SetBall',
        request_serializer=REF2CLI_dot_messages__pb2.Environment.SerializeToString,
        response_deserializer=common__pb2.Ball.FromString,
        )
    self.SetFormerRobots = channel.unary_unary(
        '/fira_message.ref_to_cli.Referee/SetFormerRobots',
        request_serializer=REF2CLI_dot_messages__pb2.Environment.SerializeToString,
        response_deserializer=REF2CLI_dot_messages__pb2.Robots.FromString,
        )
    self.SetLaterRobots = channel.unary_unary(
        '/fira_message.ref_to_cli.Referee/SetLaterRobots',
        request_serializer=REF2CLI_dot_messages__pb2.Environment.SerializeToString,
        response_deserializer=REF2CLI_dot_messages__pb2.Robots.FromString,
        )


class RefereeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunStrategy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFormerRobots(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLaterRobots(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RefereeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=REF2CLI_dot_messages__pb2.TeamInfo.FromString,
          response_serializer=REF2CLI_dot_messages__pb2.TeamName.SerializeToString,
      ),
      'RunStrategy': grpc.unary_unary_rpc_method_handler(
          servicer.RunStrategy,
          request_deserializer=REF2CLI_dot_messages__pb2.Environment.FromString,
          response_serializer=REF2CLI_dot_messages__pb2.Command.SerializeToString,
      ),
      'SetBall': grpc.unary_unary_rpc_method_handler(
          servicer.SetBall,
          request_deserializer=REF2CLI_dot_messages__pb2.Environment.FromString,
          response_serializer=common__pb2.Ball.SerializeToString,
      ),
      'SetFormerRobots': grpc.unary_unary_rpc_method_handler(
          servicer.SetFormerRobots,
          request_deserializer=REF2CLI_dot_messages__pb2.Environment.FromString,
          response_serializer=REF2CLI_dot_messages__pb2.Robots.SerializeToString,
      ),
      'SetLaterRobots': grpc.unary_unary_rpc_method_handler(
          servicer.SetLaterRobots,
          request_deserializer=REF2CLI_dot_messages__pb2.Environment.FromString,
          response_serializer=REF2CLI_dot_messages__pb2.Robots.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fira_message.ref_to_cli.Referee', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
