name: CI

on: [push]

jobs:
  build-cpp:

    runs-on: ubuntu-18.04
    
    env:
      CMAKE_CXX_COMPILER: ${{ matrix.cxx-compiler }}
      
    strategy:
      matrix:
        cxx-compiler: ["/usr/bin/clang++-7", "/usr/bin/g++"]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install protobuf and gRPC
      run: |
        sudo add-apt-repository ppa:webispy/grpc
        sudo apt-get update
        sudo apt install -y libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc clang-7
    - name: Configure
      run: |
        cmake --version
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER ../cpp
    - name: Build
      run: cmake --build build

  build-cpp-windows:
    runs-on: windows-2019
    
    env:
      WS2_32_LIBRARY: "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.18362.0\\um\\x64\\WS2_32.Lib"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install protobuf and gRPC
      run: |
        vcpkg install protobuf:x64-windows
        vcpkg install grpc:x64-windows
    - name: Fix symlink
      run: |
        Remove-Item cpp/FIRAMessage
        New-Item cpp/FIRAMessage -Value FIRAMessage -Type Junction
    - name: Configure
      run: |
        mkdir build
        cd build
        $vcpkgdir=[System.IO.Path]::GetDirectoryName((Get-Command vcpkg).Source)
        echo $vcpkgdir
        cmake --version
        cmake -D CMAKE_TOOLCHAIN_FILE=${vcpkgdir}\scripts\buildsystems\vcpkg.cmake -D VCPKG_TARGET_TRIPLET=x64-windows -D WS2_32_LIBRARY=$env:WS2_32_LIBRARY ../cpp
    - name: Build
      run: cmake --build build
