name: CI

on: [push]

jobs:
  build-cpp:

    runs-on: ${{ matrix.os }}
    
    env:
      CMAKE_CXX_COMPILER: ${{ matrix.cxx-compiler }}
      
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        cxx-compiler: ["/usr/bin/clang++", ""]
        exclude:
          - os: windows-2019
            cxx-compiler: "/usr/bin/clang++"

    steps:
    - uses: actions/checkout@v1
    - name: Install protobuf and gRPC
      run: sudo apt install -y libgrpc++-dev libprotobuf-dev
    - name: Configure
      run: |
        cmake --version
        cmake -S cpp -B build
    - name: Build
      run: cmake --build build
