name: CI

on: [push]

jobs:
  build-cpp:

    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        cxx-compiler: ["/usr/bin/clang++-7", "/usr/bin/g++"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
      with:
        submodules: recursive

    - name: Install protobuf and gRPC
      run: |
        sudo add-apt-repository ppa:webispy/grpc
        sudo apt-get update
        sudo apt install -y libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc clang-7

    - name: Build with CMake
      uses: lukka/run-cmake@v2.0
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeAppendedArgs: -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}

