name: CI

on: [push]

jobs:
  build-cpp:

    runs-on: ${{ matrix.os }}
    
    env:
      CMAKE_CXX_COMPILER: ${{ matrix.cxx-compiler }}
      
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        cxx-compiler: ["/usr/bin/clang++", ""]
        exclude:
          - os: windows-2019
            cxx-compiler: "/usr/bin/clang++"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install protobuf and gRPC
      run: sudo apt install -y libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc
    - name: Configure
      run: |
        cmake --version
        mkdir build && cd build && cmake ../cpp
    - name: Build with comiler
      run: cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER --build build
      if: ${{ matrix.cxx_compiler != '' }}
    - name: Build
      run: cmake --build build
      if: ${{ matrix.cxx_compiler == '' }}
